### ISSUE TITLE
Title of plugins in darkmode not visible

### ISSUE THREAD

**Issue by martin-lechene** [tomatophp/tomato-plugins#1]
Is a repost of [Title of plugins in darkmode not visible #22 in tomatophp/tomato](https://github.com/tomatophp/tomato/issues/22)
Holà !
This is to say that the texts in the plugin section when in dark mode (found via the demo application)

![image](https://github.com/tomatophp/tomato-plugins/assets/46826871/3ebaeab2-9801-4eab-81dc-86ee5912ad12)

Put a text-gray-xxx in dark mode instead of deleting it (as it already exists for light mode).

**Comment by fadymondy** [comment]
fixed

![image](https://github.com/tomatophp/tomato-plugins/assets/11937812/992b92fb-b8d8-4c12-a1b5-00bbb2669d89)
